language: node_js
cache: yarn
node_js:
  - lts/*
install:
  - yarn install
  - yarn build
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  skip_test: true
  on:
    tags: true
